refacto: use pivot ticket in jira service
OPEN-ENT-NG/support-pivot pull request #22
Opened 2022-12-16 08:40 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-12-16 10:35 UTC, aymericdevriesere commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +        if (!JiraConstants.NOTEXIST.equals(newModules.get(0))) {
penser à vérif que le get(0) renvoie pas null

2022-12-16 10:35 UTC, aymericdevriesere commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +        final URI urlNewTicket = JIRA_REST_API_URI.resolve(idJira + "/comment");
magic string

2022-12-16 10:35 UTC, aymericdevriesere commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +                LOGGER.error(String.format("[SupportPivot@%s::sendJiraComments] Error when add Jira comment on %s : %s - %s - %s",
il y a pas de s dans le titre de la fonction

2022-12-16 10:35 UTC, aymericdevriesere commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +                    LOGGER.error(String.format("[SupportPivot@%s::updateJiraPJ] Fail to send one Jira PJ %s",
pas le bon nom de fonction dans le error

2022-12-16 11:09 UTC, BastienBenard commented on build.gradle
> +  testCompile "io.vertx:vertx-codegen:$vertxVersion"
Utiliser pour corriger l'erreur suivante:
```
fr.openent.supportpivot.services.JiraServiceImplTest > sendJiraCommentTest FAILED
    org.mockito.exceptions.base.MockitoException:
    Mockito cannot mock this class: class io.vertx.core.http.impl.HttpClientRequestImpl.

    Mockito can only mock non-private & non-final classes.
    If you're not sure why you're getting this error, please report to the mailing list.


    Java               : 1.8
    JVM vendor name    : Oracle Corporation
    JVM vendor version : 25.151-b12
    JVM name           : OpenJDK 64-Bit Server VM
    JVM version        : 1.8.0_151-b12
    JVM info           : mixed mode
    OS name            : Linux
    OS version         : 4.9.0-6-amd64


    Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.reflect.Executable#getAnnotatedParameterTypes
        at fr.openent.supportpivot.services.JiraServiceImplTest.sendJiraCommentTest(JiraServiceImplTest.java:171)

        Caused by:
        java.lang.IllegalStateException: Error invoking java.lang.reflect.Executable#getAnnotatedParameterTypes
            at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm$AnnotatedParameterizedType.resolve(TypeDescription.java:2988)
            at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Delegator.asList(TypeDescription.java:3201)
            at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType$ForLoadedType.getDeclaredAnnotations(TypeDescription.java:5171)
            at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType$Latent.getDeclaredAnnotations(TypeDescription.java:5292)
            at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType$Latent.getDeclaredAnnotations(TypeDescription.java:5292)
            at net.bytebuddy.implementation.attribute.AnnotationAppender$ForTypeAnnotations.apply(AnnotationAppender.java:684)
            at net.bytebuddy.implementation.attribute.AnnotationAppender$ForTypeAnnotations.onParameterizedType(AnnotationAppender.java:632)
            at net.bytebuddy.implementation.attribute.AnnotationAppender$ForTypeAnnotations.onParameterizedType(AnnotationAppender.java:368)
            at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.accept(TypeDescription.java:4991)
            at net.bytebuddy.implementation.attribute.MethodAttributeAppender$ForInstrumentedMethod.apply(MethodAttributeAppender.java:208)
            at net.bytebuddy.implementation.attribute.MethodAttributeAppender$Compound.apply(MethodAttributeAppender.java:464)
            at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyAttributes(TypeWriter.java:706)
            at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:696)
            at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:605)
            at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5129)
            at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1930)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:225)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:198)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3396)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3585)
            at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:172)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
            at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
            at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
            at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
            at org.powermock.api.mockito.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:41)
            at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
            at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
            at org.mockito.Mockito.mock(Mockito.java:1908)
            at org.mockito.Mockito.mock(Mockito.java:1817)
            ... 1 more

            Caused by:
            java.lang.NullPointerException
                at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(TypeAnnotationParser.java:356)
                at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(AnnotatedTypeFactory.java:139)
                at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedParameterizedTypeImpl.<init>(AnnotatedTypeFactory.java:240)
                at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(AnnotatedTypeFactory.java:77)
                at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedTypes(TypeAnnotationParser.java:137)
                at java.lang.reflect.Executable.getAnnotatedParameterTypes(Executable.java:688)
                at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm$AnnotatedParameterizedType.resolve(TypeDescription.java:2984)
                ... 36 more
```
Lorsque l'on mock HttpClientRequest, java.lang.reflect.Executable#getAnnotatedParameterTypes va chercher a récuperer l'anotation @VertxGen qui n'est disponible qu'avec la dépendence.

2022-12-21 08:46 UTC, JinDouang requested changes

2022-12-21 08:46 UTC, JinDouang commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +            final HttpClientRequest createTicketRequest = httpClient.post(JIRA_REST_API_URI.toString(),
A envisager la possibilité d'utiliser le WebClient ?

@qperie 

Ca pourrait être intéressant

2022-12-21 08:46 UTC, JinDouang commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +            e.printStackTrace();
Que fais-tu réellement si tu as une exception ? Tu continue ton traitement malgré tout avec juste un log ?

2022-12-21 08:46 UTC, JinDouang commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +            final HttpClientRequest createTicketRequest = httpClient.post(JIRA_REST_API_URI.toString(),
Ca pourrait être un ticket pour httpClient -> WebClient

2022-12-21 08:59 UTC, BastienBenard commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +            final HttpClientRequest createTicketRequest = httpClient.post(JIRA_REST_API_URI.toString(),
Oui c'est prévu de passer en webClient [CO-1715](https://jira.support-ent.fr/browse/CO-1715)

2022-12-21 09:02 UTC, BastienBenard commented on src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
> +            e.printStackTrace();
Effectivement, je vais plutôt fail la future plutôt que d'envoyer une request malformé

2022-12-21 09:09 UTC, qpic-cgi approved these changes

2022-12-21 09:49 UTC, merged